version: '3'

services:
  app:
    container_name: warzone-node-mongo
    build: .
    ports:
      - '80:8080'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - warzoneDbData:/data/db
volumes:
  warzoneDbData:
    driver: local